In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[ 'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good' ] 


In [32]:
# define the vocabulary 
voc_size=10000

In [33]:
#on hot represnetation for every worf
one_hot_rep=[one_hot(words,voc_size) for words in sent]

In [34]:
sent
one_hot_rep

[[9145, 7729, 1351, 7136],
 [9145, 7729, 1351, 1240],
 [9145, 8265, 1351, 1681],
 [1901, 1649, 4689, 8984, 3877],
 [1901, 1649, 4689, 8984, 7840],
 [5977, 9145, 6382, 1351, 6495],
 [9216, 9369, 8594, 8984]]

In [35]:
#word embedding representation 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences 
from tensorflow.keras.models import Sequential

In [36]:
import numpy as np 

In [37]:
sent_len=8 
embedded_doc=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len) 
print(embedded_doc)


[[   0    0    0    0 9145 7729 1351 7136]
 [   0    0    0    0 9145 7729 1351 1240]
 [   0    0    0    0 9145 8265 1351 1681]
 [   0    0    0 1901 1649 4689 8984 3877]
 [   0    0    0 1901 1649 4689 8984 7840]
 [   0    0    0 5977 9145 6382 1351 6495]
 [   0    0    0    0 9216 9369 8594 8984]]


In [38]:
#feature representation 
dim=10 
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_len)) 
model.compile('adam','mse')

c:\Users\sanak\Desktop\simRNN\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [39]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[[-0.03226066, -0.0186041 , -0.01423039, -0.04191541,
         -0.03513925,  0.01039375, -0.03582734,  0.00886559,
         -0.03554609,  0.00239576],
        [-0.03226066, -0.0186041 , -0.01423039, -0.04191541,
         -0.03513925,  0.01039375, -0.03582734,  0.00886559,
         -0.03554609,  0.00239576],
        [-0.03226066, -0.0186041 , -0.01423039, -0.04191541,
         -0.03513925,  0.01039375, -0.03582734,  0.00886559,
         -0.03554609,  0.00239576],
        [-0.03226066, -0.0186041 , -0.01423039, -0.04191541,
         -0.03513925,  0.01039375, -0.03582734,  0.00886559,
         -0.03554609,  0.00239576],
        [-0.02333063,  0.00884322,  0.01103582, -0.02209098,
          0.04534168,  0.01308819, -0.00728474,  0.0262918 ,
         -0.04100718,  0.00848044],
        [-0.00312459, -0.00635127,  0.01465663,  0.04951172,
         -0.02812153, -0.01711338,  0.03077893,  0.01007692,
          0.0346774 ,  0.02532635],
        [ 0.04371378, -0.00715703,  0.0377124 ,  0.0